name: CI/CD Tienda Perritos - Backend - Ventas

on:
  push:
    branches: [ "main" ]
    paths:
      - "db/**"

jobs:
  build-push-deploy-db:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login en Amazon ECR (runner)
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: true

    - name: Build imagen Backend y push a ECR
      run: |
        cd db
        docker build -t tienda-db .
        docker tag tienda-db:latest ${{ secrets.ECR_REPO_URL_DB}}:latest
        docker push ${{ secrets.ECR_REPO_URL_DB}}:latest